# Generated by Django 2.1.3 on 2020-09-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0002_auto_20200906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(),
        ),
    ]
